WITH cte7 AS (
	SELECT TOP 7
		N	=	ROW_NUMBER() OVER (PARTITION BY (SELECT 1) ORDER BY (SELECT 1)) - 1
	FROM sys.columns
)
SELECT DATEADD(DAY, -1 * N, EOMONTH(GETDATE())) AS Dt
FROM cte7
WHERE DATENAME(WEEKDAY, DATEADD(DAY, -1 * N, EOMONTH(GETDATE()))) = 'Tuesday'
