WITH cte7 AS (
	SELECT TOP 7
		N	=	ROW_NUMBER() OVER (PARTITION BY (SELECT 1) ORDER BY (SELECT 1)) - 1
	FROM sys.columns
)
, cteLast7DaysOfMonth AS (

	SELECT DATEADD(DAY, -1 * N, EOMONTH(GETDATE())) AS Dt
		,  DATENAME(WEEKDAY, DATEADD(DAY, -1 * N, EOMONTH(GETDATE()))) AS DOW
FROM cte7
)
SELECT Dt
FROM cteLast7DaysOfMonth
WHERE DOW = 'Tuesday'
